### ISSUE TITLE
FA Connecting Bridge Cutscene

### ISSUE THREAD

**Issue by pickels25** [oct0xor/mgs2sos#10]
![FA Connecting Bridge Cutscene](https://user-images.githubusercontent.com/117943049/201192250-0c2c36c0-cc2e-461c-9bd8-d125a7fab49f.png)

When going to the FA connecting bridge for the first time from Strut A with the third person camera active, the cutscene with the cypher glitches, and Raiden runs up into the wall until the codec rings.

**Comment by Creatiw89** [comment]
had the same issue about two hours ago, thought I would write it here, but seems like you got that covered.
Lets hope we get a solution quick.

**Comment by Morsmalleo** [comment]
I'm pretty sure V's fix causes this I remember experiencing this mod long before it was even available

**Comment by pickels25** [comment]
I just loaded the game without the Solid Mods Loader and the cutscene worked as intended.

**Comment by oct0xor** [comment]
Hi! It was fixed in v1.3.0
