### ISSUE TITLE
Evasion - Clearing Camera doesnt work in 3rd Person View

### ISSUE THREAD

**Issue by pickels25** [oct0xor/mgs2sos#13]
![Evasion Clearing](https://user-images.githubusercontent.com/117943049/201490102-07bcb6d7-36c6-4360-8bfa-cdb9e137c278.png)

When in the Evasion - Clearing mode that is supposed to show the guards looking through the area, if you have the third person camera enabled it will just be the player camera.

Switching back to the default camera will sometimes fix the issue or sometimes will lead to weird outcomes like shown below.
![Evasion Clearing 2](https://user-images.githubusercontent.com/117943049/201490174-295a66f6-28dd-4ab8-b733-d8b20b0d97a0.png)

When running into another room it sometimes wont load the area in the camera.

![Evasion Clearing 3](https://user-images.githubusercontent.com/117943049/201490790-9a72311e-cbf1-4596-90d5-88845c3ed252.png)

**Comment by oct0xor** [comment]
Hi! It was fixed in v1.2.0
