### ISSUE TITLE
Add the Camera Swap Bindings to README.md

### ISSUE THREAD

**Issue by Zaphero1** [oct0xor/mgs2sos#16]
It seems some don't even realize that the mod lets you swap in and out of the fixed camera perspective, and I had to search the comments of some a youtube-video covering the mod to see it explained that 
**Triangle + R1 (or Use + Autoaim)**
is the binding and only discovered that the keyboard had it assigned to one key via trial and error
**v** (or just the autoaim key?)
Can how it's bound be added to the documentation?

**Comment by oct0xor** [comment]
Hi! I've added this info to wiki page - https://github.com/oct0xor/mgs2sos/wiki
