### ISSUE TITLE
camera just spins

### ISSUE THREAD

**Issue by psyfox42** [oct0xor/mgs2sos#2]
just installed this. tried the master release and then just the zip that had the loader and the mods folder. both result in the character moving slightly offscreen in the codec, the camera moves away during cutscenes and during gameplay the camera just spins in a circle.

**Comment by alexdperdomo** [comment]
it seems as a controller settings problem (would happen even without the mod) you should try installing "V Fix" and set your controller with it

**Comment by psyfox42** [comment]
> 

ok i have the camera working. set the control to ps2 type and it seems to be working, but there is no way to punch, grab or throw enemies.

**Comment by oct0xor** [comment]
That's all should be working, its either a controller settings problem or Steam messes things up.

**Comment by Morsmalleo** [comment]
> > 
> 
> ok i have the camera working. set the control to ps2 type and it seems to be working, but there is no way to punch, grab or throw enemies.

Can confirm this is an isolated problem because it's all working fine for me

**Comment by Morsmalleo** [comment]
> > 
> 
> ok i have the camera working. set the control to ps2 type and it seems to be working, but there is no way to punch, grab or throw enemies.

Pretty sure with PS2 controls, you need to hold the Circle ⭕ button while moving to throw enemies, and stand still or walk up behind an enemy and hold circle ⭕ to choke hold
