### ISSUE TITLE
Aspect Ratio is wrong in Widescreen Resolutions

### ISSUE THREAD

**Issue by pobgithub** [oct0xor/mgs2sos#3]
I know this is not a problem with this mod, but I have tried pairing it with old widescreen fix mods that correct the aspect ratio so the picture isn't stretched and none work together with the third person camera at the same time. Would be great to get a widescreen mod that works through the new mod loader.

**Comment by oct0xor** [comment]
[V’s fix](https://github.com/VFansss/mgs2-v-s-fix) can be used to fix the aspect ratio and it works great with this mod. First configure V’s fix with MGS2SSetup.exe and then launch the game with solid_mods_loader.exe.

**Comment by pobgithub** [comment]
Weird, it didn't work when I tried it before but it is working now. Thanks a lot for this mod and your help.
